hyeonseol00/Project_F_Server

- src/protobuf/request/battle.packet.proto
- src/protobuf/request/custom.proto
- src/protobuf/response/response.proto
> 🎉 add : 전투, 커스텀 프로토버프 작성 및 생성

- src/server.js
> ✨ update  : code update

- src/handlers/index.js
- src/handlers/town/enterDungeon.handler.js
> DungeonEnter

- src/handlers/town/enterDungeon.handler.js
> 🐛 bugfix : 던전 입장 버그 해결

- src/classes/models/user.class.js
- src/db/user/user.db.js
- src/db/user/user.queries.js
- src/handlers/town/enter.handler.js
- src/handlers/town/enterDungeon.handler.js
- src/session/user.session.js
> 🐛 bugfix : 던전 이동 시 캐릭터가 안보였었고 다른 클래스가 보였던 문제

- src/db/user/user.db.js
- src/db/user/user.queries.js
- src/handlers/town/enterDungeon.handler.js
> ✨ update : 던전 별 몬스터 3마리 소환

- src/db/user/user.queries.js
- src/handlers/index.js
- src/handlers/town/anim.handler.js
- src/handlers/town/chat.handler.js
🎉 add : anim,chat handler 추가 / index.js 수정
> 🎉 add : anim,chat handler 추가 / index.js 수정chat motion

- src/handlers/town/anim.handler.js
- src/handlers/town/chat.handler.js
> ✨ update  : anim,chat 핸들러 수정

- src/config/config.js
- src/constants/battleSceneStatus.js
- src/handlers/town/enterDungeon.handler.js
> ✨ update config 추가

- src/handlers/town/enter.handler.js
- src/handlers/town/enterDungeon.handler.js
> 🐛 bugfix : 던전 입장 시 컬럼명 변경에 의한 버그 수정

- readme.md
> 🎉 add : 리드미 추가

- readme.md
> ✨ update : 리드미 내용 추가

- readme.md
> ✨ update : 리드미 제목 변경

- src/config/config.js
- src/handlers/battle/battleFlows/getExp.battle.js
> 🐛 bugfix : 최대 레벨일 경우 아무 데이터도 없는 레벨 1 데이터를 조회하도록 수정

- src/db/game/game.db.js
- src/handlers/battle/battleFlows/getExp.battle.js
> 🩹 fix : 레벨테이블 세션화로 인한 getExp.battle.js 코드 변경

- src/handlers/battle/battleFlows/target.battle.js
> 🐛 bugfix : 몬스터 체력이 0 미만으로 떨어지는 문제 해결

- src/handlers/battle/battleFlows/getExp.battle.js
> 🐛 bugfix : 레벨테이블 잘못가져오는 버그 수정

- src/classes/models/user.class.js
- src/handlers/battle/battleFlows/switchScene/monsterAttack.switch.js
> ✨ update : 캐릭터의 회피율에 따라 몬스터의 공격을 회피하는 기능 구현

- src/handlers/battle/battleFlows/switchScene/monsterDead.switch.js
> ✨ update : 몬스터 죽는 모션

- src/handlers/battle/battleFlows/switchScene/monsterDead.switch.js
> 🐛 bugfix : 몬스터 죽는 모션 패킷 수정

- src/handlers/battle/battleFlows/switchScene/monsterAttack.switch.js
> ✨ update : 플레이어 사망 애니메이션 재생

- src/handlers/chatCommands.js
- src/handlers/town/equip.handler.js
- src/handlers/town/unequip.handler.js
> ✨ update : 장비 해제 기능 추가 및 장비 장착 할려고 할 때 레벨 제한 검증 추가

- src/classes/models/user.class.js
- src/handlers/town/equip.handler.js
> 🐛 bugfix : db 저장 방식 변경으로인한 코드 수정

- src/handlers/town/chatCommands/chatCommand.handler.js
> 🐛 bugfix : 팀 생성 시 message 값이 있을 경우 팀을 못찾는 버그

- src/classes/models/dungeon.class.js
- src/classes/models/monster.class.js
- src/handlers/town/enterDungeon.handler.js
> ♻️refactor : 몬스터 이펙트 코드 에셋데이터에서 참조

- src/handlers/town/chat.handler.js
- src/handlers/town/chatCommands/chatCommand.handler.js
> 🩹 fix : 영어로 작성된 S_Chat 한글로 통일

- src/config/config.js
- src/constants/battle/battleSceneConfig.js
- src/handlers/battle/battleFlows/gameOverLose.battle.js
> 🐛 bugfix : 플레이어 사망 시 체력 50인 상태로 마을로 귀환

- package-lock.json
- package.json
- src/config/config.js
- src/constants/env.js
- src/init/index.js
- src/init/redis.js
- src/server.js
> ✨ update : 레디스 연결

- src/assets/item.assets.js
- src/assets/level.assets.js
- src/assets/monster.assets.js
- src/classes/models/dungeon.class.js
- src/events/onEnd.js
- src/events/onError.js
- src/handlers/battle/battleFlows/action.battle.js
- src/handlers/battle/battleFlows/clearGameWin/dropItem.clearGame.js
- src/handlers/battle/battleFlows/clearGameWin/getExp.battle.js
- src/handlers/battle/battleFlows/selectItem.battle.js
- src/handlers/battle/battleFlows/switchScene/gameOverWin.switch.js
- src/handlers/town/chatCommands/item/buyItem.chat.js
- src/handlers/town/chatCommands/item/equipItem.chat.js
- src/handlers/town/chatCommands/item/sellItem.chat.js
- src/handlers/town/chatCommands/item/useItem.chat.js
- src/handlers/town/enterDungeon.handler.js
- src/init/index.js
- src/init/redis/events/redisConnect.js
- src/init/redis/redis.js
- src/utils/equip.js
- src/utils/unequip.js
> ✨ update : 에셋데이터 레디스에 저장 및 불러오기

- package-lock.json
- package.json
- src/classes/models/hatchery.class.js
- src/handlers/hatchery/attackBoss.handler.js
- src/handlers/town/enterHatchery.handler.js
> ✨ update : 동시성 처리 Bull Queue 적용

- src/Lambda/event/handler/userChat.event.js
- src/config/config.js
- src/constants/dynamoDB.js
- src/dynamoDB/connect.dynamodb.js
> 🐛 bugfix : Lambda , DynamoDB
